theme: jekyll-theme-minimal
title: Pymacaron
description: Pymacaron, a python microservice framework based on OpenAPI, Flask and pydantic, deployable to AWS Beanstalk and Google Kubernetes
logo: logo.png
show_downloads: "true"
